import pandas as pd

def compute_danger_score(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    
    # Use the probability columns generated by score_batter_props.py
    df["danger_score"] = (
        df["hr_prob"] * 3.0 +
        df["hit_prob"] * 1.0 +
        df["multi_prob"] * 2.0 -
        df["k_prob"] * 0.5
    )
    return df

def aggregate_game_matchups(game_group: pd.DataFrame) -> pd.DataFrame:
    agg = (
        game_group.groupby(["batter_name", "pitcher_name"], dropna=False)
        .agg({
            "hit_prob": "mean",  # Use mean instead of sum for probabilities
            "hr_prob": "mean",
            "k_prob": "mean",
            "multi_prob": "mean",
        })
        .reset_index()
    )
    return agg


def build_top20_embeds(mdf, discord_module):
    df = compute_danger_score(mdf)

    # Only keep rows that were scored by the model
    if {"hit_prob", "hr_prob", "multi_prob", "k_prob"}.issubset(df.columns):
        df = df.dropna(subset=["hit_prob", "hr_prob", "multi_prob", "k_prob"], how="all")

    # Sort by highest danger score, then by team names for stable ordering
    if "home_team_name" in df.columns and "away_team_name" in df.columns:
        df = df.sort_values(["danger_score", "home_team_name", "away_team_name"], ascending=[False, True, True])
    else:
        df = df.sort_values("danger_score", ascending=False)
    df = df.head(20)

    lines = []
    for _, r in df.iterrows():
        batter = r["batter_name"]
        pitcher = r["pitcher_name"]

        # Convert ML probabilities into readable percentages
        hits = f"{r['hit_prob'] * 100:.1f}%"
        hrs = f"{r['hr_prob'] * 100:.1f}%"
        sos = f"{r['k_prob'] * 100:.1f}%"
        multi = f"{r['multi_prob'] * 100:.1f}%"

        line = f"🧢 **{batter}** vs {pitcher} — H: {hits} | HR: {hrs} | SO: {sos} | M: {multi}"
        lines.append(line)

    CHUNK = 10
    embeds = []
    labels = []

    for i in range(0, len(lines), CHUNK):
        chunk = lines[i:i+CHUNK]
        desc = "\n".join(chunk)

        embed = discord_module.Embed(
            title="Top 20 Danger‑Score Matchups",
            description=desc,
            color=0xFFD700,
        )

        embeds.append(embed)
        labels.append(f"Top 20 (part {i//CHUNK + 1})")

    return embeds, labels


def build_danger_score_for_game(game_group, discord_module):
    agg = aggregate_game_matchups(game_group)
    agg = compute_danger_score(agg)
    agg = agg.sort_values("danger_score", ascending=False)

    lines = []
    for _, r in agg.iterrows():
        batter = r["batter_name"]
        pitcher = r["pitcher_name"]

        # Convert ML probabilities into readable percentages
        hits = f"{r['hit_prob'] * 100:.1f}%"
        hrs = f"{r['hr_prob'] * 100:.1f}%"
        sos = f"{r['k_prob'] * 100:.1f}%"
        multi = f"{r['multi_prob'] * 100:.1f}%"

        line = f"🧢 **{batter}** vs {pitcher} — H: {hits} | HR: {hrs} | SO: {sos} | M: {multi}"
        lines.append(line)

    home = game_group["home_team_name"].iloc[0]
    away = game_group["away_team_name"].iloc[0]
    game_date = game_group["game_date"].iloc[0]

    embed = discord_module.Embed(
        title=f"{away} @ {home} — Danger Score",
        description="\n".join(lines) if lines else "No matchups found.",
        color=0xFF4500,
    )
    embed.set_footer(text=f"Date: {game_date}")

    return embed
